<h2>Wykłady</h2>

<p>Autentyczną podstawą wszystkich szkół buddyjskich są trzy poziomy nauk, przekazane dwa i&nbsp;pół tysiąca lat temu przez Buddę Siakjamuniego, które opowiadają potrzebom różnych jego uczniów. Wszystkim, którzy chcieli uniknąć cierpienia, Budda wyjaśniał prawo przyczyny i&nbsp;skutku – ten zbiór nauk nosi nazwę Małej Drogi (skr.&nbsp;Hinajana).<br>

    Ludziom o&nbsp;większym potencjale udzielał nauk o&nbsp;współczuciu i&nbsp;mądrości – znanych dzisiaj jako Wielka Droga (skr. Mahajana). Tym zaś, którzy posiadali spontaniczne zaufanie do własnej natury buddy, udzielił nauk <span style="color:#d20025">Diamentowej Drogi (skr. Wadżrajana)</span>.</p><hr>

<h3>Mała Droga – Hinajana</h3>
<p>Nauki te wskazują na przemijalność myśli, uczuć oraz własnego ciała, a&nbsp;co za tym idzie, iluzoryczność własnej, odrębnej tożsamości. Mówią, że istnienie rzeczywistego „ja” jest iluzją. Przekazują wiedzę o działaniach przynoszących cierpienie oraz wyjaśniają, jak im zaradzić, uczą też medytacji, które dają wewnętrzny spokój i&nbsp;dystans. Celem tej ścieżki jest wyzwolenie.</p><hr>
<h3>Wielka Droga – Mahajana</h3> 
<p>Nauki te pokazują, jak wzmocnić w&nbsp;sobie współczucie do takiego poziomu, na którym potrafimy zrozumieć położenie innych, jednocześnie rozwijając zawartą w naszym umyśle mądrość. Gdy zaczniemy dostrzegać to, co&nbsp;naprawdę się wydarza, bez obaw i&nbsp;oczekiwań będziemy mogli pomagać innym z&nbsp;nieosobistym nastawieniem. Celem tej ścieżki jest osiągnięcie oświecenia dla dobra wszystkich.</p><hr>
<h3>Diamentowa Droga – Wadżrajana </h3>
<p>Nauki te opierają się na poglądzie, że wszystko jest w&nbsp;swej naturze doskonałe i&nbsp;wszystkie istoty mają ten sam najwyższy potencjał. Na&nbsp;tym poziomie wszystkie nauki Buddy, dotyczące poglądu i&nbsp;medytacji, prowadzą uczniów do odkrycia, że&nbsp;umysł w&nbsp;swej naturze jest wolny od wszelkich ograniczeń. Podstawowe właściwości umysłu – jego świadomość, moc i&nbsp;zdolność do przeżywania inspiracji – są dla praktykującego bramą do rozpoznania natury umysłu. Ze&nbsp;stanu rozpoznania, że umysł posiada naturę przestrzeni i jest niezniszczalny, wyłaniają się same z&nbsp;siebie radość i&nbsp;aktywna miłość, które wyrażają się w&nbsp;postaci pożytecznych działań. 
Zachowania te inspirują otoczenie i&nbsp;budzą w&nbsp;innych zaufanie, że oni również mogą urzeczywistnić ten poziom. Najlepszy i&nbsp;najbardziej wszechstronny kontakt z&nbsp;własną naturą umysłu możemy osiągnąć dzięki medytacji na&nbsp;nauczyciela, który reprezentuje Buddę i&nbsp;jego nauki. Diamentowa Droga to wyjątkowo szybka ścieżka rozwoju, ponieważ wykorzystuje wszystkie możliwości ciała, mowy i&nbsp;umysłu. Jest w&nbsp;stanie przekształcić nasze pożyteczne pragnienia, idealistyczne podejście do&nbsp;życia i&nbsp;uczucie przyjaźni w&nbsp;kroki na ścieżce do oświecenia. Jej podstawą jest chęć rozwoju dla dobra wszystkich istot, a&nbsp;celem – osiągnięcie oświecenia.</p>

